# MYSQL service deployment
apiVersion: v1
kind: Service
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud
spec:
  ports:
    - port: 3306
  selector:
    app: owncloud
    tier: mariadb
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: owncloud-mariadb
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: mariadb
    spec:
      containers:
      - image: mariadb:latest
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-password
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mariadb
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
# Put db-host owncloud-mariadb and password my-password on initial of Owncloud
---
# owncloud service deployment
apiVersion: v1
kind: Service
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  ports:
    - port: 80
  selector:
    app: owncloud
    tier: ownc-frontend
#  type: LoadBalancer
# Remove by Ingress
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: owncloud-pv-claim
  labels:
    app: owncloud
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: owncloud
  labels:
    app: owncloud
spec:
  selector:
    matchLabels:
      app: owncloud
      tier: ownc-frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: owncloud
        tier: ownc-frontend
    spec:
      containers:
      - image: owncloud:latest
        name: owncloud
        ports:
        - containerPort: 80
          name: owncloud
        volumeMounts:
        - name: owncloud-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: owncloud-persistent-storage
        persistentVolumeClaim:
          claimName: owncloud-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: owncloud
  labels:
    name: owncloud
spec:
  rules:
  - host: "owncloud.domain.com" # Replace host with your domain for ingress service !!!
    http:
      paths:
      - path: /
        backend:
          serviceName: owncloud
          servicePort: 80