apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo
        tier: demo
    spec:
      containers:
      - image: hydrog3n/minerd
        name: demo
        env:
         - name: USERNAME
           value: ccXtwf2xUdUbS9rqYRa7iuwNW2yWh7rAYw
         - name: URL
           value: stratum+tcp://pool.chaucha.cl
         - name: PORT
           value: '3008'
         - name: PASSWORD
           value: 'fdbv1291fdbv0824'
        resources:
          requests:
            cpu: "1000m"
          limits:
            cpu: "4000m"
