apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seeder-pv-claim
  namespace: seeder
  labels:
    app: seeder
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 500Gi